// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxmjgnmmkflvecgwxgwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4bWpnbm1ta2ZsdmVjZ3d4Z3d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Mzk1MjEsImV4cCI6MjA2NjUxNTUyMX0.i2FJioFC9ijNFy-Es2FRGiuPavZ3NhjnpxcE6hELISk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});